apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-statefulset
spec:
  selector:
    matchLabels:
      app: wordpress-app
  serviceName: wordpress-service
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: mariadb-service:3306
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: wordpress
        volumeMounts:
          - name: wordpress-pvc
            mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: wordpress-pvc
      spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: manual
          selector:
            matchLabels:
              app: wordpress
          resources:
            requests:
              storage: 1Gi
